version: 0.0
os: linux

files:
  - source: ./
    destination: /home/ubuntu

hooks:
  ApplcationStop:
    - location: ./applicationStop.sh
      timeout: 300

  AfterInstall:
    - location: ./afterInstall.sh
      timeout: 300

  ApplicationStart:
    - location: ./applicationStart.sh
<<<<<<< HEAD
      timeout: 300      
=======
      timeout: 100      
>>>>>>> 486952e471b36d31d11c07ebac75125d67bc125e
