version: 2
jobs:
  pr_check:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: Install npm command
          command: 'npm install'
      - run:
          name: Starting node
          command: 'npm test'
  build:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: Installing NPM
          command: 'npm install'
      - run:
          name: Starting node test
          command: 'npm test'
  deploy:
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - checkout        
      - run:
          name: Updating apt-get
          command: sudo apt-get update
      - run:
          name: Installing wget
          command: 'sudo apt-get install wget zip unzip'
      - run:
          name: Installing aws cli
          command: sudo pip install awscli
      - run:
          name: Compress web app
          command: |
            aws configure set default.region us-east-1
            mkdir -p webapp_zip
            cp codedeploy_scripts/*.sh .
            zip -r webapp.zip API *.sh *.yml *.json *.js
            mv webapp.zip webapp_zip/
      - run:
          name: Upload Artifact to S3 bucket
          command: |
            aws s3 cp webapp_zip/webapp.zip s3://${S3_BUCKET_ADDR}/artifacts/webapp.zip
      - run:
          name: AWS CodeDeploy call
          command: |
            aws deploy register-application-revision --application-name billmanagement-webapp --s3-location bucket=${S3_BUCKET_ADDR},bundleType=zip,key=artifacts/webapp.zip
            aws deploy create-deployment --application-name billmanagement-webapp --deployment-group-name billmanagement-webapp-deployment --s3-location bucket=${S3_BUCKET_ADDR},bundleType=zip,key=artifacts/webapp.zip --deployment-config-name CodeDeployDefault.AllAtOnce 



workflows:
  version: 2
  pr-check:
    jobs:
    - pr_check
  build_deploy:
    jobs:
    - build:
        filters:
          branches:
            only: master
    - deploy:
        filters:
          branches:
            only: master            