version: 2
jobs:
  pr_check:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: Install npm command
          command: 'npm --version'
  build:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: Install npm command
          command: 'npm --version'
workflows:
  version: 2
  pr-check:
    jobs:
    - pr_check 
  build_deploy:
    jobs:
    - build:
        filters:
          branches:
            only: master